accounts:
- psmnext/accounts/*
- psmnext/controllers/accounts_controller.py
- psmnext/controllers/taxes_and_totals.py

stock:
- psmnext/stock/*
- psmnext/controllers/stock_controller.py
- psmnext/controllers/item_variant.py

assets:
- psmnext/assets/*

regional:
- psmnext/regional/*

selling:
- psmnext/selling/*
- psmnext/controllers/selling_controller.py

buying:
- psmnext/buying/*
- psmnext/controllers/buying_controller.py

support:
- psmnext/support/*

POS:
- pos*

ecommerce:
- psmnext/e_commerce/*

maintenance:
- psmnext/maintenance/*

manufacturing:
- psmnext/manufacturing/*

crm:
- psmnext/crm/*

HR:
- psmnext/hr/*

payroll:
- psmnext/payroll*

projects:
- psmnext/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['psmnext/**/*.py']
  all: ['!psmnext/**/test*.py']
